guild:
  items-create:
    item1:
      material: EMERALD_BLOCK
      amount: 32
    item2:
      material: DIAMOND_BLOCK
      amount: 32
tablist:
  element:
    header: "&6Simple header"
    footer: "&aSimple footer"
    slot:
      8: "&a8 slot"