name: 'NatalciaGuildsPlugin'
version: ${project.version}
main: 'xyz.yooniks.natalciaguilds.bukkit.NatalciaGuildsPlugin'
authors: [yooniks]
description: 'Simple spigot plugin implementation for NatalciaGuilds'
website: 'www.youtube.com/c/Enchanted3'
